export const LOGIN_ACESS = 'LOGIN_ACESS';
export const REQUEST_API_SUCESS = 'REQUEST_API_SUCESS';
export const ADD_EXPENSES = 'ADD_EXPENSES';
export const DELETE_EXPENSES = 'DELETE_EXPENSES';
export const EDIT_EXPENSE_START = 'EDIT_EXPENSE_START';
export const EDIT_EXPENSE_FINISH = 'EDIT_EXPENSE_FINISH';
